### ISSUE TITLE
Item equip slots are not properly assigned.

### ISSUE THREAD

**Issue by sdasd30** [DrDoak/TourismGame#11]
Item slot 1 is bound to 'K', not 'J', item slot 2 is bound to 'L' not 'K'. Item slot 3 is nonfunctional.

**Comment by DrDoak** [comment]
Fixed in commit c5f6420

Control Scheme is now J to ; from left to right for Items 1-4. Even though right now you don't have a 4th weapon slot.

Interaction is now "F". And Inventory is "E". This will be our test control scheme until we have remmapable controls.
