### ISSUE TITLE
Camera flicks to other player_debug when changing rooms.

### ISSUE THREAD

**Issue by sdasd30** [DrDoak/TourismGame#12]
Probably nonissue, as the gameplay does not usually have more than one player in a room.

**Comment by DrDoak** [comment]
Solution seems to mostly work as of 30920f5 . Still bugs the first time. But every subsequent time it works? Investigate further later

**Comment by DrDoak** [comment]
Now Aggressively searches for a character when loading a new room. Which resolves this issue when starting. But does not aggressivey search when leaving a room or when a character dies.
