### ISSUE TITLE
Items can disappear from the inventory after being moved around.

### ISSUE THREAD

**Issue by sdasd30** [DrDoak/TourismGame#16]
To recreate this bug.
Pick up the floor sword.
Open inventory, drop the item
Pick the sword back up.
Equip the sword.
Close inventory.
Open inventory.
Sword is missing.

**Comment by sdasd30** [comment]
This also occurs if you open your inventory the first time, move the sword to any slot, then close and reopen the inventory.

**Comment by DrDoak** [comment]
I was not able to get this. Maybe try again after a pull?

**Comment by sdasd30** [comment]
Seems to work fine now.
