### ISSUE TITLE
Picking up items resets action data.

### ISSUE THREAD

**Issue by sdasd30** [DrDoak/TourismGame#18]
I set the sword to have a hitbox and knockback. Upon picking up and equipping, they are all set to 0. The item works when values are set manually after equipped.

**Comment by DrDoak** [comment]
Fixed in commit 451e45e. 

The issue was that the knife's knockback and damage were set in the PREFAB. Remember from now on that the properties in the prefab are very important and what is recreated when the item goes in and out of the inventory
