### ISSUE TITLE
Falling off things is very fast

### ISSUE THREAD

**Issue by sdasd30** [DrDoak/TourismGame#20]
When you jump, you fall at a reasonable speed. When you fall off the stage or the box, you fall at a ludicrous speed.

**Comment by DrDoak** [comment]
Gravity is now adjusted in 51c2986026ce9d44b91b1b065a73d3be43d7ac0b. Please test to confirm

**Comment by DrDoak** [comment]
Okay. Standard gravity for players will be set to 0.5.
