### ISSUE TITLE
Interacting with other people causes mini inventories to appear.

### ISSUE THREAD

**Issue by sdasd30** [DrDoak/TourismGame#23]
See this picture.
![image](https://user-images.githubusercontent.com/16390995/61192182-817d2d80-a680-11e9-9362-2fb842e8611f.png)

**Comment by DrDoak** [comment]
Not supposed to interact with Other characters in the first place. Prevented that so issue is no longer present. (for now). May need to review later if we decide to be able to interact with characters.
