### ISSUE TITLE
Swapping item to another occupied item slot causes weird bugginess.

### ISSUE THREAD

**Issue by sdasd30** [DrDoak/TourismGame#30]
1. It causes the item that is not held to disappear from the inventory. but only after closing the inventory and reopening it.
2. The replaced item is still visible in the player's hand, despite not appearing in their inventory.
3. The item slot originally occupied by the first item held still retains the properties of that item, despite it being in a new slot.

**Comment by DrDoak** [comment]
Mostly resolved mechanically in commit c46a6ab9b15e1c9019c05d4fc92a75719ed9eb20. Parts 1 and 3 are resolved. Part 2 is still there

**Comment by DrDoak** [comment]
Part 2 fixed in 2a05589
