### ISSUE TITLE
Many errors upon opening on my computer

### ISSUE THREAD

**Issue by sdasd30** [DrDoak/TourismGame#6]
It could be related to using the wrong version of unity (I'm using 3.0a8). I cannot find the 3.0a3 version. Can you update it and see if it still works?

**Comment by DrDoak** [comment]
UPdated version to 3.0a8. Also removed Render Pipeline issues. please check if working

**Comment by sdasd30** [comment]
Only one error, here it is. It is a compiler error, preventing me from running. 

Library\PackageCache\com.unity.render-pipelines.lightweight@6.7.1\Runtime\LightweightRenderPipeline.cs(117,46): error CS0122: 'VFXManager' is inaccessible due to its protection level

**Comment by sdasd30** [comment]
Actually, this is my bad, I did not properly pull. Fixed when pulled.
